# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
import os

from setuptools import setup, find_packages  # noqa: H301

NAME = "pyrebrickable_data"
VERSION = os.environ.get('TRAVIS_TAG', os.environ.get('TAG_NAME', 'dev'))

REQUIRES = ['sqlalchemy', 'appdirs', 'requests', 'click']

setup(
    name=NAME,
    version=VERSION,
    description="""This is rebrickable_data, providing a wrapper around rebrickable data
    
It uses the monthly data dumps (http://www.rebrickable.com/downloads) and provides
SQLAlchemy models to query the data inside

You gain access to the rebrickable-data cli :

`rebrickable-data download` to download csv files from rebrickable
`rebrickable-data import` to import them in a database

see examples in examples folder
""",
    author_email="",
    url="",
    keywords=["LEGO","Rebrickable", "SQL"],
    entry_points={
        'console_scripts': [
            'rebrickable-data=rebrickable_data.cli:main'
        ]
    },
    install_requires=REQUIRES,
    include_package_data=True,
    packages=find_packages()
)
