# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""
import os

from setuptools import setup, find_packages  # noqa: H301

NAME = "pyrebrickable_data"
VERSION = os.environ.get('TRAVIS_TAG', os.environ.get('TAG_NAME', 'dev'))

REQUIRES = ["pyrebrickable_api", 'sqlalchemy', 'appdirs', 'requests']

setup(
    name=NAME,
    version=VERSION,
    description="""This is rebrickable_data, providing a wrapper around rebrickable data
    
It uses the monthly data dumps (http://www.rebrickable.com/downloads) and provides
sqlalchemy models to query it 
""",
    author_email="",
    url="",
    keywords=["Swagger", ""],
    install_requires=REQUIRES,
    include_package_data=True,
    packages=find_packages()
)
