# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import rebrickable
from rebrickable.api.lego_api import LegoApi  # noqa: E501
from rebrickable.rest import ApiException


class TestLegoApi(unittest.TestCase):
    """LegoApi unit test stubs"""

    def setUp(self):
        self.api = rebrickable.api.lego_api.LegoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_lego_colors_list(self):
        """Test case for lego_colors_list

        Get a list of all Colors.  # noqa: E501
        """
        pass

    def test_lego_colors_read(self):
        """Test case for lego_colors_read

        Get details about a specific Color.  # noqa: E501
        """
        pass

    def test_lego_elements_read(self):
        """Test case for lego_elements_read

        Get details about a specific Element ID.  # noqa: E501
        """
        pass

    def test_lego_mocs_parts_list(self):
        """Test case for lego_mocs_parts_list

        Get a list of all Inventory Parts in this MOC.  # noqa: E501
        """
        pass

    def test_lego_mocs_read(self):
        """Test case for lego_mocs_read

        Get details for a specific MOC.  # noqa: E501
        """
        pass

    def test_lego_part_categories_list(self):
        """Test case for lego_part_categories_list

        Get a list of all Part Categories.  # noqa: E501
        """
        pass

    def test_lego_part_categories_read(self):
        """Test case for lego_part_categories_read

        Get details about a specific Part Category.  # noqa: E501
        """
        pass

    def test_lego_parts_colors_list(self):
        """Test case for lego_parts_colors_list

        Get a list of all Colors a Part has appeared in.  # noqa: E501
        """
        pass

    def test_lego_parts_colors_read(self):
        """Test case for lego_parts_colors_read

        Get details about a specific Part/Color combination.  # noqa: E501
        """
        pass

    def test_lego_parts_colors_sets_list(self):
        """Test case for lego_parts_colors_sets_list

        Get a list of all Sets the Part/Color combination has appeard in.  # noqa: E501
        """
        pass

    def test_lego_parts_list(self):
        """Test case for lego_parts_list

        Get a list of Parts.  # noqa: E501
        """
        pass

    def test_lego_parts_read(self):
        """Test case for lego_parts_read

        Get details about a specific Part.  # noqa: E501
        """
        pass

    def test_lego_sets_alternates_list(self):
        """Test case for lego_sets_alternates_list

        Get a list of MOCs which are Alternate Builds of a specific Set - i.e. all parts in the MOC can  # noqa: E501
        """
        pass

    def test_lego_sets_list(self):
        """Test case for lego_sets_list

        Get a list of Sets, optionally filtered by any of the below parameters.  # noqa: E501
        """
        pass

    def test_lego_sets_parts_list(self):
        """Test case for lego_sets_parts_list

        Get a list of all Inventory Parts in this Set.  # noqa: E501
        """
        pass

    def test_lego_sets_read(self):
        """Test case for lego_sets_read

        Get details for a specific Set.  # noqa: E501
        """
        pass

    def test_lego_sets_sets_list(self):
        """Test case for lego_sets_sets_list

        Get a list of all Inventory Sets in this Set.  # noqa: E501
        """
        pass

    def test_lego_themes_list(self):
        """Test case for lego_themes_list

        Return all Themes  # noqa: E501
        """
        pass

    def test_lego_themes_read(self):
        """Test case for lego_themes_read

        Return details for a specific Theme  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
