# put env TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/ for testing

TAG_NAME:=${TAG_NAME}
TRAVIS_TAG:=${TRAVIS_TAG}
TRAVIS_BRANCH:=${TRAVIS_BRANCH}
VERSION ?= $(if $(TRAVIS_TAG),$(TRAVIS_TAG),$(if $(TAG_NAME),$(TAG_NAME),dev))

deploy_pypi:
ifdef VERSION
	rm -rf dist

	python3 api/setup.py sdist bdist_wheel
	python3 cli/setup.py sdist bdist_wheel
	python3 data/setup.py sdist bdist_wheel
	python3 setup.py sdist bdist_wheel

	twine upload -u ${PYPI_USER} -p ${PYPI_PASSWORD} dist/*
else
	@echo "not tagged"
endif

validate_spec:
	prance validate swagger.json

generate_api:
	python3 patch_swagger.py

	echo -- `cat swagger.json`

	docker run --rm --user `id -u`:`id -g` -v ${PWD}:/local openapitools/openapi-generator-cli:v3.2.2 \
	           generate -i /local/swagger.json \
	           --git-user-id rienafairefr \
	           --git-repo-id pyrebrickable \
	           -g python -o /local/api -DprojectName=pyrebrickable_api -DpackageName=rebrickable_api \
	           -DpackageVersion="$(VERSION)" -DappDescription="This is rebrickable_api, an autogenerated package to access www.rebrickable.com"\
	           -DappName="pyrebrickable-api" -DinfoEmail="rienafairefr@gmail.com" \

	docker run --rm --user `id -u`:`id -g` -v ${PWD}:/local openapitools/openapi-generator-cli:v3.2.2 \
	        generate -i /local/swagger.json \
	        -g openapi-yaml -o /local/api-yaml -DprojectName=pyrebrickable_api -DpackageName=rebrickable_api \
	        -DpackageVersion="$(VERSION)" -DappDescription="This is rebrickable_api, an autogenerated package to access www.rebrickable.com"\
	        -DappName="pyrebrickable-api" -DinfoEmail="rienafairefr@gmail.com" \


build_docs:
	set -e
	pip install -r docs-requirements.txt
	make -C docs html

deploy_docs: build_docs
	#python -m doctr deploy docs

	#python -m doctr deploy --sync --require-master  --built-docs docs/_build/html "."
	#python -m doctr deploy --sync --no-require-master  --built-docs docs/_build/html "docs-$(TRAVIS_BRANCH)"
