# put env TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/ for testing

upload_pypi:
ifdef TRAVIS_TAG
	rm -rf dist

	python pyrebrickable-api/setup.py sdist bdist_wheel
	python pyrebrickable-cli/setup.py sdist bdist_wheel
	python pyrebrickable-data/setup.py sdist bdist_wheel
	python setup.py sdist bdist_wheel

	twine upload -u ${PYPI_USER} -p ${PYPI_PASSWORD} dist/*
else
	@echo "not tagged"
endif

validate_spec:
	prance validate swagger.json

generate_api:
	python patch_swagger.py

	echo -- `cat swagger.json`

	VERSION=${TRAVIS_TAG:-${TAG_NAME:-dev}}

	docker run --rm --user `id -u`:`id -g` -v ${PWD}:/local swaggerapi/swagger-codegen-cli:v2.3.0 \
	           generate -i /local/swagger.json \
	           --git-user-id rienafairefr \
	           --git-repo-id pyrebrickable \
	           -l python -o /local/pyrebrickable-api -DprojectName=pyrebrickable_api -DpackageName=rebrickable_api \
	           -DpackageVersion="$VERSION" -DappDescription="This is rebrickable_api, an autogenerated package to access www.rebrickable.com"\
	           -DappName="pyrebrickable-api" -DinfoEmail="rienafairefr@gmail.com" \

docs_build:
	set -e
	pip install -r docs-requirements.txt
	make -C docs html

	python -m doctr deploy docs

	python -m doctr deploy --sync --require-master  --built-docs docs/_build/html "."
	python -m doctr deploy --sync --no-require-master  --built-docs docs/_build/html "docs-$TRAVIS_BRANCH"