# coding: utf-8

"""
    

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from rebrickable.api_client import ApiClient


class LegoApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def lego_colors_list(self, **kwargs):  # noqa: E501
        """Get a list of all Colors.  # noqa: E501

        Get a list of all Colors.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_colors_list(async=True)
        >>> result = thread.get()

        :param async bool
        :param str page: null
        :param str page_size: null
        :param str ordering: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_colors_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.lego_colors_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def lego_colors_list_with_http_info(self, **kwargs):  # noqa: E501
        """Get a list of all Colors.  # noqa: E501

        Get a list of all Colors.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_colors_list_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str page: null
        :param str page_size: null
        :param str ordering: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page', 'page_size', 'ordering']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_colors_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501
        if 'ordering' in params:
            query_params.append(('ordering', params['ordering']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/colors/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_colors_read(self, id, **kwargs):  # noqa: E501
        """Get details about a specific Color.  # noqa: E501

        Get details about a specific Color.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_colors_read(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_colors_read_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.lego_colors_read_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def lego_colors_read_with_http_info(self, id, **kwargs):  # noqa: E501
        """Get details about a specific Color.  # noqa: E501

        Get details about a specific Color.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_colors_read_with_http_info(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_colors_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `lego_colors_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/colors/{id}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_elements_read(self, element_id, **kwargs):  # noqa: E501
        """Get details about a specific Element ID.  # noqa: E501

        Get details about a specific Element ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_elements_read(element_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str element_id: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_elements_read_with_http_info(element_id, **kwargs)  # noqa: E501
        else:
            (data) = self.lego_elements_read_with_http_info(element_id, **kwargs)  # noqa: E501
            return data

    def lego_elements_read_with_http_info(self, element_id, **kwargs):  # noqa: E501
        """Get details about a specific Element ID.  # noqa: E501

        Get details about a specific Element ID.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_elements_read_with_http_info(element_id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str element_id: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['element_id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_elements_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'element_id' is set
        if ('element_id' not in params or
                params['element_id'] is None):
            raise ValueError("Missing the required parameter `element_id` when calling `lego_elements_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'element_id' in params:
            path_params['element_id'] = params['element_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/elements/{element_id}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_mocs_parts_list(self, set_num, **kwargs):  # noqa: E501
        """Get a list of all Inventory Parts in this MOC.  # noqa: E501

        Get a list of all Inventory Parts in this MOC.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_mocs_parts_list(set_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str set_num: null (required)
        :param str page: null
        :param str page_size: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_mocs_parts_list_with_http_info(set_num, **kwargs)  # noqa: E501
        else:
            (data) = self.lego_mocs_parts_list_with_http_info(set_num, **kwargs)  # noqa: E501
            return data

    def lego_mocs_parts_list_with_http_info(self, set_num, **kwargs):  # noqa: E501
        """Get a list of all Inventory Parts in this MOC.  # noqa: E501

        Get a list of all Inventory Parts in this MOC.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_mocs_parts_list_with_http_info(set_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str set_num: null (required)
        :param str page: null
        :param str page_size: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['set_num', 'page', 'page_size']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_mocs_parts_list" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'set_num' is set
        if ('set_num' not in params or
                params['set_num'] is None):
            raise ValueError("Missing the required parameter `set_num` when calling `lego_mocs_parts_list`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'set_num' in params:
            path_params['set_num'] = params['set_num']  # noqa: E501

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/mocs/{set_num}/parts/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_mocs_read(self, set_num, **kwargs):  # noqa: E501
        """Get details for a specific MOC.  # noqa: E501

        Get details for a specific MOC.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_mocs_read(set_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str set_num: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_mocs_read_with_http_info(set_num, **kwargs)  # noqa: E501
        else:
            (data) = self.lego_mocs_read_with_http_info(set_num, **kwargs)  # noqa: E501
            return data

    def lego_mocs_read_with_http_info(self, set_num, **kwargs):  # noqa: E501
        """Get details for a specific MOC.  # noqa: E501

        Get details for a specific MOC.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_mocs_read_with_http_info(set_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str set_num: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['set_num']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_mocs_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'set_num' is set
        if ('set_num' not in params or
                params['set_num'] is None):
            raise ValueError("Missing the required parameter `set_num` when calling `lego_mocs_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'set_num' in params:
            path_params['set_num'] = params['set_num']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/mocs/{set_num}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_part_categories_list(self, **kwargs):  # noqa: E501
        """Get a list of all Part Categories.  # noqa: E501

        Get a list of all Part Categories.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_part_categories_list(async=True)
        >>> result = thread.get()

        :param async bool
        :param str page: null
        :param str page_size: null
        :param str ordering: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_part_categories_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.lego_part_categories_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def lego_part_categories_list_with_http_info(self, **kwargs):  # noqa: E501
        """Get a list of all Part Categories.  # noqa: E501

        Get a list of all Part Categories.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_part_categories_list_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str page: null
        :param str page_size: null
        :param str ordering: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page', 'page_size', 'ordering']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_part_categories_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501
        if 'ordering' in params:
            query_params.append(('ordering', params['ordering']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/part_categories/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_part_categories_read(self, id, **kwargs):  # noqa: E501
        """Get details about a specific Part Category.  # noqa: E501

        Get details about a specific Part Category.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_part_categories_read(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_part_categories_read_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.lego_part_categories_read_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def lego_part_categories_read_with_http_info(self, id, **kwargs):  # noqa: E501
        """Get details about a specific Part Category.  # noqa: E501

        Get details about a specific Part Category.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_part_categories_read_with_http_info(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_part_categories_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `lego_part_categories_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/part_categories/{id}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_parts_colors_list(self, part_num, **kwargs):  # noqa: E501
        """Get a list of all Colors a Part has appeared in.  # noqa: E501

        Get a list of all Colors a Part has appeared in.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_parts_colors_list(part_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str part_num: null (required)
        :param str page: null
        :param str page_size: null
        :param str ordering: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_parts_colors_list_with_http_info(part_num, **kwargs)  # noqa: E501
        else:
            (data) = self.lego_parts_colors_list_with_http_info(part_num, **kwargs)  # noqa: E501
            return data

    def lego_parts_colors_list_with_http_info(self, part_num, **kwargs):  # noqa: E501
        """Get a list of all Colors a Part has appeared in.  # noqa: E501

        Get a list of all Colors a Part has appeared in.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_parts_colors_list_with_http_info(part_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str part_num: null (required)
        :param str page: null
        :param str page_size: null
        :param str ordering: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['part_num', 'page', 'page_size', 'ordering']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_parts_colors_list" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'part_num' is set
        if ('part_num' not in params or
                params['part_num'] is None):
            raise ValueError("Missing the required parameter `part_num` when calling `lego_parts_colors_list`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'part_num' in params:
            path_params['part_num'] = params['part_num']  # noqa: E501

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501
        if 'ordering' in params:
            query_params.append(('ordering', params['ordering']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/parts/{part_num}/colors/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_parts_colors_read(self, color_id, part_num, **kwargs):  # noqa: E501
        """Get details about a specific Part/Color combination.  # noqa: E501

        Get details about a specific Part/Color combination.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_parts_colors_read(color_id, part_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str color_id: null (required)
        :param str part_num: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_parts_colors_read_with_http_info(color_id, part_num, **kwargs)  # noqa: E501
        else:
            (data) = self.lego_parts_colors_read_with_http_info(color_id, part_num, **kwargs)  # noqa: E501
            return data

    def lego_parts_colors_read_with_http_info(self, color_id, part_num, **kwargs):  # noqa: E501
        """Get details about a specific Part/Color combination.  # noqa: E501

        Get details about a specific Part/Color combination.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_parts_colors_read_with_http_info(color_id, part_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str color_id: null (required)
        :param str part_num: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['color_id', 'part_num']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_parts_colors_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'color_id' is set
        if ('color_id' not in params or
                params['color_id'] is None):
            raise ValueError("Missing the required parameter `color_id` when calling `lego_parts_colors_read`")  # noqa: E501
        # verify the required parameter 'part_num' is set
        if ('part_num' not in params or
                params['part_num'] is None):
            raise ValueError("Missing the required parameter `part_num` when calling `lego_parts_colors_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'color_id' in params:
            path_params['color_id'] = params['color_id']  # noqa: E501
        if 'part_num' in params:
            path_params['part_num'] = params['part_num']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/parts/{part_num}/colors/{color_id}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_parts_colors_sets_list(self, color_id, part_num, **kwargs):  # noqa: E501
        """Get a list of all Sets the Part/Color combination has appeard in.  # noqa: E501

        Get a list of all Sets the Part/Color combination has appeard in.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_parts_colors_sets_list(color_id, part_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str color_id: null (required)
        :param str part_num: null (required)
        :param str page: null
        :param str page_size: null
        :param str ordering: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_parts_colors_sets_list_with_http_info(color_id, part_num, **kwargs)  # noqa: E501
        else:
            (data) = self.lego_parts_colors_sets_list_with_http_info(color_id, part_num, **kwargs)  # noqa: E501
            return data

    def lego_parts_colors_sets_list_with_http_info(self, color_id, part_num, **kwargs):  # noqa: E501
        """Get a list of all Sets the Part/Color combination has appeard in.  # noqa: E501

        Get a list of all Sets the Part/Color combination has appeard in.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_parts_colors_sets_list_with_http_info(color_id, part_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str color_id: null (required)
        :param str part_num: null (required)
        :param str page: null
        :param str page_size: null
        :param str ordering: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['color_id', 'part_num', 'page', 'page_size', 'ordering']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_parts_colors_sets_list" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'color_id' is set
        if ('color_id' not in params or
                params['color_id'] is None):
            raise ValueError("Missing the required parameter `color_id` when calling `lego_parts_colors_sets_list`")  # noqa: E501
        # verify the required parameter 'part_num' is set
        if ('part_num' not in params or
                params['part_num'] is None):
            raise ValueError("Missing the required parameter `part_num` when calling `lego_parts_colors_sets_list`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'color_id' in params:
            path_params['color_id'] = params['color_id']  # noqa: E501
        if 'part_num' in params:
            path_params['part_num'] = params['part_num']  # noqa: E501

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501
        if 'ordering' in params:
            query_params.append(('ordering', params['ordering']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/parts/{part_num}/colors/{color_id}/sets/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_parts_list(self, **kwargs):  # noqa: E501
        """Get a list of Parts.  # noqa: E501

        Get a list of Parts.  Optionally filter by one or more of the below query parameters.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_parts_list(async=True)
        >>> result = thread.get()

        :param async bool
        :param str page: null
        :param str page_size: null
        :param str part_num: null
        :param str part_cat_id: null
        :param str color_id: null
        :param str bricklink_id: null
        :param str brickowl_id: null
        :param str lego_id: null
        :param str ldraw_id: null
        :param str ordering: null
        :param str search: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_parts_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.lego_parts_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def lego_parts_list_with_http_info(self, **kwargs):  # noqa: E501
        """Get a list of Parts.  # noqa: E501

        Get a list of Parts.  Optionally filter by one or more of the below query parameters.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_parts_list_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str page: null
        :param str page_size: null
        :param str part_num: null
        :param str part_cat_id: null
        :param str color_id: null
        :param str bricklink_id: null
        :param str brickowl_id: null
        :param str lego_id: null
        :param str ldraw_id: null
        :param str ordering: null
        :param str search: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page', 'page_size', 'part_num', 'part_cat_id', 'color_id', 'bricklink_id', 'brickowl_id', 'lego_id', 'ldraw_id', 'ordering', 'search']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_parts_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501
        if 'part_num' in params:
            query_params.append(('part_num', params['part_num']))  # noqa: E501
        if 'part_cat_id' in params:
            query_params.append(('part_cat_id', params['part_cat_id']))  # noqa: E501
        if 'color_id' in params:
            query_params.append(('color_id', params['color_id']))  # noqa: E501
        if 'bricklink_id' in params:
            query_params.append(('bricklink_id', params['bricklink_id']))  # noqa: E501
        if 'brickowl_id' in params:
            query_params.append(('brickowl_id', params['brickowl_id']))  # noqa: E501
        if 'lego_id' in params:
            query_params.append(('lego_id', params['lego_id']))  # noqa: E501
        if 'ldraw_id' in params:
            query_params.append(('ldraw_id', params['ldraw_id']))  # noqa: E501
        if 'ordering' in params:
            query_params.append(('ordering', params['ordering']))  # noqa: E501
        if 'search' in params:
            query_params.append(('search', params['search']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/parts/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_parts_read(self, part_num, **kwargs):  # noqa: E501
        """Get details about a specific Part.  # noqa: E501

        Get details about a specific Part.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_parts_read(part_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str part_num: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_parts_read_with_http_info(part_num, **kwargs)  # noqa: E501
        else:
            (data) = self.lego_parts_read_with_http_info(part_num, **kwargs)  # noqa: E501
            return data

    def lego_parts_read_with_http_info(self, part_num, **kwargs):  # noqa: E501
        """Get details about a specific Part.  # noqa: E501

        Get details about a specific Part.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_parts_read_with_http_info(part_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str part_num: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['part_num']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_parts_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'part_num' is set
        if ('part_num' not in params or
                params['part_num'] is None):
            raise ValueError("Missing the required parameter `part_num` when calling `lego_parts_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'part_num' in params:
            path_params['part_num'] = params['part_num']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/parts/{part_num}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_sets_alternates_list(self, set_num, **kwargs):  # noqa: E501
        """Get a list of MOCs which are Alternate Builds of a specific Set - i.e. all parts in the MOC can  # noqa: E501

        Get a list of MOCs which are Alternate Builds of a specific Set - i.e. all parts in the MOC can be found in the Set.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_sets_alternates_list(set_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str set_num: null (required)
        :param str page: null
        :param str page_size: null
        :param str ordering: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_sets_alternates_list_with_http_info(set_num, **kwargs)  # noqa: E501
        else:
            (data) = self.lego_sets_alternates_list_with_http_info(set_num, **kwargs)  # noqa: E501
            return data

    def lego_sets_alternates_list_with_http_info(self, set_num, **kwargs):  # noqa: E501
        """Get a list of MOCs which are Alternate Builds of a specific Set - i.e. all parts in the MOC can  # noqa: E501

        Get a list of MOCs which are Alternate Builds of a specific Set - i.e. all parts in the MOC can be found in the Set.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_sets_alternates_list_with_http_info(set_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str set_num: null (required)
        :param str page: null
        :param str page_size: null
        :param str ordering: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['set_num', 'page', 'page_size', 'ordering']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_sets_alternates_list" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'set_num' is set
        if ('set_num' not in params or
                params['set_num'] is None):
            raise ValueError("Missing the required parameter `set_num` when calling `lego_sets_alternates_list`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'set_num' in params:
            path_params['set_num'] = params['set_num']  # noqa: E501

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501
        if 'ordering' in params:
            query_params.append(('ordering', params['ordering']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/sets/{set_num}/alternates/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_sets_list(self, **kwargs):  # noqa: E501
        """Get a list of Sets, optionally filtered by any of the below parameters.  # noqa: E501

        Get a list of Sets, optionally filtered by any of the below parameters.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_sets_list(async=True)
        >>> result = thread.get()

        :param async bool
        :param str page: null
        :param str page_size: null
        :param str theme_id: null
        :param str min_year: null
        :param str max_year: null
        :param str min_parts: null
        :param str max_parts: null
        :param str ordering: null
        :param str search: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_sets_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.lego_sets_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def lego_sets_list_with_http_info(self, **kwargs):  # noqa: E501
        """Get a list of Sets, optionally filtered by any of the below parameters.  # noqa: E501

        Get a list of Sets, optionally filtered by any of the below parameters.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_sets_list_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str page: null
        :param str page_size: null
        :param str theme_id: null
        :param str min_year: null
        :param str max_year: null
        :param str min_parts: null
        :param str max_parts: null
        :param str ordering: null
        :param str search: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page', 'page_size', 'theme_id', 'min_year', 'max_year', 'min_parts', 'max_parts', 'ordering', 'search']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_sets_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501
        if 'theme_id' in params:
            query_params.append(('theme_id', params['theme_id']))  # noqa: E501
        if 'min_year' in params:
            query_params.append(('min_year', params['min_year']))  # noqa: E501
        if 'max_year' in params:
            query_params.append(('max_year', params['max_year']))  # noqa: E501
        if 'min_parts' in params:
            query_params.append(('min_parts', params['min_parts']))  # noqa: E501
        if 'max_parts' in params:
            query_params.append(('max_parts', params['max_parts']))  # noqa: E501
        if 'ordering' in params:
            query_params.append(('ordering', params['ordering']))  # noqa: E501
        if 'search' in params:
            query_params.append(('search', params['search']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/sets/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_sets_parts_list(self, set_num, **kwargs):  # noqa: E501
        """Get a list of all Inventory Parts in this Set.  # noqa: E501

        Get a list of all Inventory Parts in this Set.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_sets_parts_list(set_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str set_num: null (required)
        :param str page: null
        :param str page_size: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_sets_parts_list_with_http_info(set_num, **kwargs)  # noqa: E501
        else:
            (data) = self.lego_sets_parts_list_with_http_info(set_num, **kwargs)  # noqa: E501
            return data

    def lego_sets_parts_list_with_http_info(self, set_num, **kwargs):  # noqa: E501
        """Get a list of all Inventory Parts in this Set.  # noqa: E501

        Get a list of all Inventory Parts in this Set.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_sets_parts_list_with_http_info(set_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str set_num: null (required)
        :param str page: null
        :param str page_size: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['set_num', 'page', 'page_size']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_sets_parts_list" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'set_num' is set
        if ('set_num' not in params or
                params['set_num'] is None):
            raise ValueError("Missing the required parameter `set_num` when calling `lego_sets_parts_list`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'set_num' in params:
            path_params['set_num'] = params['set_num']  # noqa: E501

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/sets/{set_num}/parts/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_sets_read(self, set_num, **kwargs):  # noqa: E501
        """Get details for a specific Set.  # noqa: E501

        Get details for a specific Set.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_sets_read(set_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str set_num: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_sets_read_with_http_info(set_num, **kwargs)  # noqa: E501
        else:
            (data) = self.lego_sets_read_with_http_info(set_num, **kwargs)  # noqa: E501
            return data

    def lego_sets_read_with_http_info(self, set_num, **kwargs):  # noqa: E501
        """Get details for a specific Set.  # noqa: E501

        Get details for a specific Set.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_sets_read_with_http_info(set_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str set_num: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['set_num']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_sets_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'set_num' is set
        if ('set_num' not in params or
                params['set_num'] is None):
            raise ValueError("Missing the required parameter `set_num` when calling `lego_sets_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'set_num' in params:
            path_params['set_num'] = params['set_num']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/sets/{set_num}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_sets_sets_list(self, set_num, **kwargs):  # noqa: E501
        """Get a list of all Inventory Sets in this Set.  # noqa: E501

        Get a list of all Inventory Sets in this Set.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_sets_sets_list(set_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str set_num: null (required)
        :param str page: null
        :param str page_size: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_sets_sets_list_with_http_info(set_num, **kwargs)  # noqa: E501
        else:
            (data) = self.lego_sets_sets_list_with_http_info(set_num, **kwargs)  # noqa: E501
            return data

    def lego_sets_sets_list_with_http_info(self, set_num, **kwargs):  # noqa: E501
        """Get a list of all Inventory Sets in this Set.  # noqa: E501

        Get a list of all Inventory Sets in this Set.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_sets_sets_list_with_http_info(set_num, async=True)
        >>> result = thread.get()

        :param async bool
        :param str set_num: null (required)
        :param str page: null
        :param str page_size: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['set_num', 'page', 'page_size']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_sets_sets_list" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'set_num' is set
        if ('set_num' not in params or
                params['set_num'] is None):
            raise ValueError("Missing the required parameter `set_num` when calling `lego_sets_sets_list`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'set_num' in params:
            path_params['set_num'] = params['set_num']  # noqa: E501

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/sets/{set_num}/sets/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_themes_list(self, **kwargs):  # noqa: E501
        """Return all Themes  # noqa: E501

        Return all Themes  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_themes_list(async=True)
        >>> result = thread.get()

        :param async bool
        :param str page: null
        :param str page_size: null
        :param str ordering: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_themes_list_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.lego_themes_list_with_http_info(**kwargs)  # noqa: E501
            return data

    def lego_themes_list_with_http_info(self, **kwargs):  # noqa: E501
        """Return all Themes  # noqa: E501

        Return all Themes  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_themes_list_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str page: null
        :param str page_size: null
        :param str ordering: null
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['page', 'page_size', 'ordering']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_themes_list" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'page' in params:
            query_params.append(('page', params['page']))  # noqa: E501
        if 'page_size' in params:
            query_params.append(('page_size', params['page_size']))  # noqa: E501
        if 'ordering' in params:
            query_params.append(('ordering', params['ordering']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/themes/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def lego_themes_read(self, id, **kwargs):  # noqa: E501
        """Return details for a specific Theme  # noqa: E501

        Return details for a specific Theme  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_themes_read(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.lego_themes_read_with_http_info(id, **kwargs)  # noqa: E501
        else:
            (data) = self.lego_themes_read_with_http_info(id, **kwargs)  # noqa: E501
            return data

    def lego_themes_read_with_http_info(self, id, **kwargs):  # noqa: E501
        """Return details for a specific Theme  # noqa: E501

        Return details for a specific Theme  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.lego_themes_read_with_http_info(id, async=True)
        >>> result = thread.get()

        :param async bool
        :param str id: null (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method lego_themes_read" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `lego_themes_read`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/v3/lego/themes/{id}/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
