# coding: utf-8

"""
    

     This is pyrebrickable, a python CLI wrapper around the Rebrickable API<br> <br> It supports the v3 API through it's openAPI specification.<br> https://rebrickable.com/api/v3/swagger/?format=openapi<br> Models for Part, Set, etc. have been manually added to provide meaningful results from HTTP responses<br> <br> Some endpoints might not work, don't hesitate to file an issue<br>   # noqa: E501

    OpenAPI spec version: 
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SetList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'num_sets': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'num_sets': 'num_sets'
    }

    def __init__(self, id=None, name=None, num_sets=None):  # noqa: E501
        """SetList - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._num_sets = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if num_sets is not None:
            self.num_sets = num_sets

    @property
    def id(self):
        """Gets the id of this SetList.  # noqa: E501


        :return: The id of this SetList.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SetList.


        :param id: The id of this SetList.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this SetList.  # noqa: E501


        :return: The name of this SetList.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SetList.


        :param name: The name of this SetList.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def num_sets(self):
        """Gets the num_sets of this SetList.  # noqa: E501


        :return: The num_sets of this SetList.  # noqa: E501
        :rtype: int
        """
        return self._num_sets

    @num_sets.setter
    def num_sets(self, num_sets):
        """Sets the num_sets of this SetList.


        :param num_sets: The num_sets of this SetList.  # noqa: E501
        :type: int
        """

        self._num_sets = num_sets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SetList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
