# coding: utf-8

import pprint
import re  # noqa: F401

import six


class Badge(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'code': 'String',
        'descr': 'String',
        'id': 'Integer',
        'level': 'Integer',
        'name': 'String'
    }

    attribute_map = {
        'code': 'code',
        'descr': 'descr',
        'id': 'id',
        'level': 'level',
        'name': 'name'
    }

    def __init__(self, code=null, descr=null, id=null, level=null, name=null):  # noqa: E501
        """Badge - a model defined in OpenAPI"""  # noqa: E501

        self._code = None
        self._descr = None
        self._id = None
        self._level = None
        self._name = None
        self.discriminator = None

        if code is not None:
            self.code = code
        if descr is not None:
            self.descr = descr
        if id is not None:
            self.id = id
        if level is not None:
            self.level = level
        if name is not None:
            self.name = name

    @property
    def code(self):
        """Gets the code of this Badge.  # noqa: E501


        :return: The code of this Badge.  # noqa: E501
        :rtype: String
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this Badge.


        :param code: The code of this Badge.  # noqa: E501
        :type: String
        """

        self._code = code

    @property
    def descr(self):
        """Gets the descr of this Badge.  # noqa: E501


        :return: The descr of this Badge.  # noqa: E501
        :rtype: String
        """
        return self._descr

    @descr.setter
    def descr(self, descr):
        """Sets the descr of this Badge.


        :param descr: The descr of this Badge.  # noqa: E501
        :type: String
        """

        self._descr = descr

    @property
    def id(self):
        """Gets the id of this Badge.  # noqa: E501


        :return: The id of this Badge.  # noqa: E501
        :rtype: Integer
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Badge.


        :param id: The id of this Badge.  # noqa: E501
        :type: Integer
        """

        self._id = id

    @property
    def level(self):
        """Gets the level of this Badge.  # noqa: E501


        :return: The level of this Badge.  # noqa: E501
        :rtype: Integer
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this Badge.


        :param level: The level of this Badge.  # noqa: E501
        :type: Integer
        """

        self._level = level

    @property
    def name(self):
        """Gets the name of this Badge.  # noqa: E501


        :return: The name of this Badge.  # noqa: E501
        :rtype: String
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Badge.


        :param name: The name of this Badge.  # noqa: E501
        :type: String
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Badge):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
