# coding: utf-8

import pprint
import re  # noqa: F401

import six


class ExternalColorId(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'extUnderscoredescrs': 'List',
        'extUnderscoreids': 'List'
    }

    attribute_map = {
        'extUnderscoredescrs': 'ext_descrs',
        'extUnderscoreids': 'ext_ids'
    }

    def __init__(self, extUnderscoredescrs=null, extUnderscoreids=null):  # noqa: E501
        """ExternalColorId - a model defined in OpenAPI"""  # noqa: E501

        self._extUnderscoredescrs = None
        self._extUnderscoreids = None
        self.discriminator = None

        if extUnderscoredescrs is not None:
            self.extUnderscoredescrs = extUnderscoredescrs
        if extUnderscoreids is not None:
            self.extUnderscoreids = extUnderscoreids

    @property
    def extUnderscoredescrs(self):
        """Gets the extUnderscoredescrs of this ExternalColorId.  # noqa: E501


        :return: The extUnderscoredescrs of this ExternalColorId.  # noqa: E501
        :rtype: List
        """
        return self._extUnderscoredescrs

    @extUnderscoredescrs.setter
    def extUnderscoredescrs(self, extUnderscoredescrs):
        """Sets the extUnderscoredescrs of this ExternalColorId.


        :param extUnderscoredescrs: The extUnderscoredescrs of this ExternalColorId.  # noqa: E501
        :type: List
        """

        self._extUnderscoredescrs = extUnderscoredescrs

    @property
    def extUnderscoreids(self):
        """Gets the extUnderscoreids of this ExternalColorId.  # noqa: E501


        :return: The extUnderscoreids of this ExternalColorId.  # noqa: E501
        :rtype: List
        """
        return self._extUnderscoreids

    @extUnderscoreids.setter
    def extUnderscoreids(self, extUnderscoreids):
        """Sets the extUnderscoreids of this ExternalColorId.


        :param extUnderscoreids: The extUnderscoreids of this ExternalColorId.  # noqa: E501
        :type: List
        """

        self._extUnderscoreids = extUnderscoreids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExternalColorId):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
