# coding: utf-8

import pprint
import re  # noqa: F401

import six


class Rewards(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'badges': 'List',
        'level': 'Integer',
        'points': 'Integer'
    }

    attribute_map = {
        'badges': 'badges',
        'level': 'level',
        'points': 'points'
    }

    def __init__(self, badges=null, level=null, points=null):  # noqa: E501
        """Rewards - a model defined in OpenAPI"""  # noqa: E501

        self._badges = None
        self._level = None
        self._points = None
        self.discriminator = None

        if badges is not None:
            self.badges = badges
        if level is not None:
            self.level = level
        if points is not None:
            self.points = points

    @property
    def badges(self):
        """Gets the badges of this Rewards.  # noqa: E501


        :return: The badges of this Rewards.  # noqa: E501
        :rtype: List
        """
        return self._badges

    @badges.setter
    def badges(self, badges):
        """Sets the badges of this Rewards.


        :param badges: The badges of this Rewards.  # noqa: E501
        :type: List
        """

        self._badges = badges

    @property
    def level(self):
        """Gets the level of this Rewards.  # noqa: E501


        :return: The level of this Rewards.  # noqa: E501
        :rtype: Integer
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this Rewards.


        :param level: The level of this Rewards.  # noqa: E501
        :type: Integer
        """

        self._level = level

    @property
    def points(self):
        """Gets the points of this Rewards.  # noqa: E501


        :return: The points of this Rewards.  # noqa: E501
        :rtype: Integer
        """
        return self._points

    @points.setter
    def points(self, points):
        """Sets the points of this Rewards.


        :param points: The points of this Rewards.  # noqa: E501
        :type: Integer
        """

        self._points = points

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Rewards):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
