# coding: utf-8

import pprint
import re  # noqa: F401

import six


class Theme(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'Integer',
        'name': 'String',
        'parentUnderscoreid': 'Integer'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'parentUnderscoreid': 'parent_id'
    }

    def __init__(self, id=null, name=null, parentUnderscoreid=null):  # noqa: E501
        """Theme - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._name = None
        self._parentUnderscoreid = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if parentUnderscoreid is not None:
            self.parentUnderscoreid = parentUnderscoreid

    @property
    def id(self):
        """Gets the id of this Theme.  # noqa: E501


        :return: The id of this Theme.  # noqa: E501
        :rtype: Integer
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Theme.


        :param id: The id of this Theme.  # noqa: E501
        :type: Integer
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Theme.  # noqa: E501


        :return: The name of this Theme.  # noqa: E501
        :rtype: String
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Theme.


        :param name: The name of this Theme.  # noqa: E501
        :type: String
        """

        self._name = name

    @property
    def parentUnderscoreid(self):
        """Gets the parentUnderscoreid of this Theme.  # noqa: E501


        :return: The parentUnderscoreid of this Theme.  # noqa: E501
        :rtype: Integer
        """
        return self._parentUnderscoreid

    @parentUnderscoreid.setter
    def parentUnderscoreid(self, parentUnderscoreid):
        """Sets the parentUnderscoreid of this Theme.


        :param parentUnderscoreid: The parentUnderscoreid of this Theme.  # noqa: E501
        :type: Integer
        """

        self._parentUnderscoreid = parentUnderscoreid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Theme):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
