# coding: utf-8

import pprint
import re  # noqa: F401

import six


class UsersTokenResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'userUnderscoretoken': 'String'
    }

    attribute_map = {
        'userUnderscoretoken': 'user_token'
    }

    def __init__(self, userUnderscoretoken=null):  # noqa: E501
        """UsersTokenResponse - a model defined in OpenAPI"""  # noqa: E501

        self._userUnderscoretoken = None
        self.discriminator = None

        if userUnderscoretoken is not None:
            self.userUnderscoretoken = userUnderscoretoken

    @property
    def userUnderscoretoken(self):
        """Gets the userUnderscoretoken of this UsersTokenResponse.  # noqa: E501


        :return: The userUnderscoretoken of this UsersTokenResponse.  # noqa: E501
        :rtype: String
        """
        return self._userUnderscoretoken

    @userUnderscoretoken.setter
    def userUnderscoretoken(self, userUnderscoretoken):
        """Sets the userUnderscoretoken of this UsersTokenResponse.


        :param userUnderscoretoken: The userUnderscoretoken of this UsersTokenResponse.  # noqa: E501
        :type: String
        """

        self._userUnderscoretoken = userUnderscoretoken

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UsersTokenResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
